import webbrowser
import os

# Define the HTML content
html_content = """
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Generated HTML Page</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            display: flex;
            justify-content: center;
            align-items: center;
            height: 100vh;
            margin: 0;
            background-color: #f0f0f0;
        }
        .container {
            text-align: center;
            padding: 20px;
            background-color: white;
            border-radius: 8px;
            box-shadow: 0 0 10px rgba(0,0,0,0.1);
        }
    </style>
</head>
<body>
    <div class="container">
        <h1>Hello from Python!</h1>
        <p>This HTML file was generated by a Python script and opened in your browser.</p>
    </div>
</body>
</html>
"""

# Define the output file path
output_file = "generated_page.html"

# Write the HTML content to a file
with open(output_file, "w") as file:
    file.write(html_content)

# Get the absolute path of the HTML file
absolute_path = os.path.abspath(output_file)

# Open the HTML file in the default web browser
webbrowser.open(f"file://{absolute_path}")

print(f"HTML file '{output_file}' has been generated and opened in your default browser.")